### ISSUE TITLE
如何打包其他项目

### ISSUE THREAD

**Issue by zhangjinmiao** [xjtushilei/Webhooks#1]
？ 怎么使用

**Comment by xjtushilei** [comment]
比如你的代码在 github 上，每次 push 上去，github 自带的 webhook 就会就触发一个服务器的指令。这个指令就是自动从服务器拉取最新的代码，然后编译打包，然后 mv 到这个程序需要到的地方，然后替换，有必要重启容器也可以，最后就运行了。
